//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JogoMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaTemas
    {
        public int Id { get; set; }
        public Nullable<int> SalaId { get; set; }
        public Nullable<int> TemaId { get; set; }
    
        public virtual Sala Sala { get; set; }
        public virtual Tema Tema { get; set; }
    }
}
